security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider

            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

            logout:
                path: /api/logout

            # ✅ THIS must be inside api firewall
            entry_point: security.authenticator.json_login.api

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password

            logout:
                path: app_logout

    access_control:
      # PUBLIC
      - { path: ^/api/login, roles: PUBLIC_ACCESS }
      - { path: ^/api/register, roles: PUBLIC_ACCESS }

      # SECURED
      - { path: ^/api/order, roles: ROLE_USER }
      - { path: ^/api/product, roles: ROLE_WORKER }
      - { path: ^/api, roles: ROLE_USER }

      # WEB
      - { path: ^/login, roles: PUBLIC_ACCESS }
      - { path: ^/register, roles: PUBLIC_ACCESS }
